CREATE TABLE IF NOT EXISTS PRICES (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    BRAND_ID BIGINT NOT NULL,
    START_DATE TIMESTAMP NOT NULL,
    END_DATE TIMESTAMP NOT NULL,
    PRICE_LIST INTEGER NOT NULL,
    PRODUCT_ID BIGINT NOT NULL,
    PRIORITY INTEGER NOT NULL,
    PRICE DECIMAL(10,2) NOT NULL,
    CURR CHAR(3) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_prices_product_brand_dates ON PRICES (PRODUCT_ID, BRAND_ID, START_DATE, END_DATE);
